# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wessley/ml/v1/chat.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'wessley/ml/v1/chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18wessley/ml/v1/chat.proto\x12\rwessley.ml.v1\"\xbd\x01\n\x0b\x43hatRequest\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\x12\x18\n\x07\x63ontext\x18\x02 \x03(\tR\x07\x63ontext\x12#\n\rsystem_prompt\x18\x03 \x01(\tR\x0csystemPrompt\x12 \n\x0btemperature\x18\x04 \x01(\x02R\x0btemperature\x12\x14\n\x05model\x18\x05 \x01(\tR\x05model\x12\x1d\n\nmax_tokens\x18\x06 \x01(\x05R\tmaxTokens\"[\n\x0c\x43hatResponse\x12\x14\n\x05reply\x18\x01 \x01(\tR\x05reply\x12\x1f\n\x0btokens_used\x18\x02 \x01(\x05R\ntokensUsed\x12\x14\n\x05model\x18\x03 \x01(\tR\x05model\"3\n\tChatChunk\x12\x12\n\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n\x04\x64one\x18\x02 \x01(\x08R\x04\x64one2\x94\x01\n\x0b\x43hatService\x12?\n\x04\x43hat\x12\x1a.wessley.ml.v1.ChatRequest\x1a\x1b.wessley.ml.v1.ChatResponse\x12\x44\n\nChatStream\x12\x1a.wessley.ml.v1.ChatRequest\x1a\x18.wessley.ml.v1.ChatChunk0\x01\x42\x1bZ\x19wessley-mvp/ml/proto;mlpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wessley.ml.v1.chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031wessley-mvp/ml/proto;mlpb'
  _globals['_CHATREQUEST']._serialized_start=44
  _globals['_CHATREQUEST']._serialized_end=233
  _globals['_CHATRESPONSE']._serialized_start=235
  _globals['_CHATRESPONSE']._serialized_end=326
  _globals['_CHATCHUNK']._serialized_start=328
  _globals['_CHATCHUNK']._serialized_end=379
  _globals['_CHATSERVICE']._serialized_start=382
  _globals['_CHATSERVICE']._serialized_end=530
# @@protoc_insertion_point(module_scope)
