# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from wessley.ml.v1 import chat_pb2 as wessley_dot_ml_dot_v1_dot_chat__pb2


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/wessley.ml.v1.ChatService/Chat',
                request_serializer=wessley_dot_ml_dot_v1_dot_chat__pb2.ChatRequest.SerializeToString,
                response_deserializer=wessley_dot_ml_dot_v1_dot_chat__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ChatStream = channel.unary_stream(
                '/wessley.ml.v1.ChatService/ChatStream',
                request_serializer=wessley_dot_ml_dot_v1_dot_chat__pb2.ChatRequest.SerializeToString,
                response_deserializer=wessley_dot_ml_dot_v1_dot_chat__pb2.ChatChunk.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=wessley_dot_ml_dot_v1_dot_chat__pb2.ChatRequest.FromString,
                    response_serializer=wessley_dot_ml_dot_v1_dot_chat__pb2.ChatResponse.SerializeToString,
            ),
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=wessley_dot_ml_dot_v1_dot_chat__pb2.ChatRequest.FromString,
                    response_serializer=wessley_dot_ml_dot_v1_dot_chat__pb2.ChatChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wessley.ml.v1.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wessley.ml.v1.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wessley.ml.v1.ChatService/Chat',
            wessley_dot_ml_dot_v1_dot_chat__pb2.ChatRequest.SerializeToString,
            wessley_dot_ml_dot_v1_dot_chat__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/wessley.ml.v1.ChatService/ChatStream',
            wessley_dot_ml_dot_v1_dot_chat__pb2.ChatRequest.SerializeToString,
            wessley_dot_ml_dot_v1_dot_chat__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
