# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wessley/ml/v1/embed.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'wessley/ml/v1/embed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19wessley/ml/v1/embed.proto\x12\rwessley.ml.v1\"\"\n\x0c\x45mbedRequest\x12\x12\n\x04text\x18\x01 \x01(\tR\x04text\"G\n\rEmbedResponse\x12\x16\n\x06values\x18\x01 \x03(\x02R\x06values\x12\x1e\n\ndimensions\x18\x02 \x01(\x05R\ndimensions\")\n\x11\x45mbedBatchRequest\x12\x14\n\x05texts\x18\x01 \x03(\tR\x05texts\"R\n\x12\x45mbedBatchResponse\x12<\n\nembeddings\x18\x01 \x03(\x0b\x32\x1c.wessley.ml.v1.EmbedResponseR\nembeddings2\xa5\x01\n\x0c\x45mbedService\x12\x42\n\x05\x45mbed\x12\x1b.wessley.ml.v1.EmbedRequest\x1a\x1c.wessley.ml.v1.EmbedResponse\x12Q\n\nEmbedBatch\x12 .wessley.ml.v1.EmbedBatchRequest\x1a!.wessley.ml.v1.EmbedBatchResponseB\x1bZ\x19wessley-mvp/ml/proto;mlpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wessley.ml.v1.embed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031wessley-mvp/ml/proto;mlpb'
  _globals['_EMBEDREQUEST']._serialized_start=44
  _globals['_EMBEDREQUEST']._serialized_end=78
  _globals['_EMBEDRESPONSE']._serialized_start=80
  _globals['_EMBEDRESPONSE']._serialized_end=151
  _globals['_EMBEDBATCHREQUEST']._serialized_start=153
  _globals['_EMBEDBATCHREQUEST']._serialized_end=194
  _globals['_EMBEDBATCHRESPONSE']._serialized_start=196
  _globals['_EMBEDBATCHRESPONSE']._serialized_end=278
  _globals['_EMBEDSERVICE']._serialized_start=281
  _globals['_EMBEDSERVICE']._serialized_end=446
# @@protoc_insertion_point(module_scope)
