# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from wessley.ml.v1 import embed_pb2 as wessley_dot_ml_dot_v1_dot_embed__pb2


class EmbedServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Embed = channel.unary_unary(
                '/wessley.ml.v1.EmbedService/Embed',
                request_serializer=wessley_dot_ml_dot_v1_dot_embed__pb2.EmbedRequest.SerializeToString,
                response_deserializer=wessley_dot_ml_dot_v1_dot_embed__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.EmbedBatch = channel.unary_unary(
                '/wessley.ml.v1.EmbedService/EmbedBatch',
                request_serializer=wessley_dot_ml_dot_v1_dot_embed__pb2.EmbedBatchRequest.SerializeToString,
                response_deserializer=wessley_dot_ml_dot_v1_dot_embed__pb2.EmbedBatchResponse.FromString,
                _registered_method=True)


class EmbedServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=wessley_dot_ml_dot_v1_dot_embed__pb2.EmbedRequest.FromString,
                    response_serializer=wessley_dot_ml_dot_v1_dot_embed__pb2.EmbedResponse.SerializeToString,
            ),
            'EmbedBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedBatch,
                    request_deserializer=wessley_dot_ml_dot_v1_dot_embed__pb2.EmbedBatchRequest.FromString,
                    response_serializer=wessley_dot_ml_dot_v1_dot_embed__pb2.EmbedBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wessley.ml.v1.EmbedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wessley.ml.v1.EmbedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbedService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wessley.ml.v1.EmbedService/Embed',
            wessley_dot_ml_dot_v1_dot_embed__pb2.EmbedRequest.SerializeToString,
            wessley_dot_ml_dot_v1_dot_embed__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wessley.ml.v1.EmbedService/EmbedBatch',
            wessley_dot_ml_dot_v1_dot_embed__pb2.EmbedBatchRequest.SerializeToString,
            wessley_dot_ml_dot_v1_dot_embed__pb2.EmbedBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
