# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\rwessley.ml.v1\"~\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x03(\t\x12\x15\n\rsystem_prompt\x18\x03 \x01(\t\x12\x13\n\x0btemperature\x18\x04 \x01(\x02\x12\r\n\x05model\x18\x05 \x01(\t\x12\x12\n\nmax_tokens\x18\x06 \x01(\x05\"A\n\x0c\x43hatResponse\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x13\n\x0btokens_used\x18\x02 \x01(\x05\x12\r\n\x05model\x18\x03 \x01(\t\"\'\n\tChatChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\x32\x94\x01\n\x0b\x43hatService\x12?\n\x04\x43hat\x12\x1a.wessley.ml.v1.ChatRequest\x1a\x1b.wessley.ml.v1.ChatResponse\x12\x44\n\nChatStream\x12\x1a.wessley.ml.v1.ChatRequest\x1a\x18.wessley.ml.v1.ChatChunk0\x01\x42\x1bZ\x19wessley-mvp/ml/proto;mlpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031wessley-mvp/ml/proto;mlpb'
  _globals['_CHATREQUEST']._serialized_start=29
  _globals['_CHATREQUEST']._serialized_end=155
  _globals['_CHATRESPONSE']._serialized_start=157
  _globals['_CHATRESPONSE']._serialized_end=222
  _globals['_CHATCHUNK']._serialized_start=224
  _globals['_CHATCHUNK']._serialized_end=263
  _globals['_CHATSERVICE']._serialized_start=266
  _globals['_CHATSERVICE']._serialized_end=414
# @@protoc_insertion_point(module_scope)
