// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wessley/ml/v1/chat.proto

package mlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Context       []string               `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Temperature   float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,6,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_wessley_ml_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wessley_ml_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_wessley_ml_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetContext() []string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ChatRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *ChatRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,2,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_wessley_ml_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wessley_ml_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_wessley_ml_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *ChatResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *ChatResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ChatChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatChunk) Reset() {
	*x = ChatChunk{}
	mi := &file_wessley_ml_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChunk) ProtoMessage() {}

func (x *ChatChunk) ProtoReflect() protoreflect.Message {
	mi := &file_wessley_ml_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChunk.ProtoReflect.Descriptor instead.
func (*ChatChunk) Descriptor() ([]byte, []int) {
	return file_wessley_ml_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ChatChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_wessley_ml_v1_chat_proto protoreflect.FileDescriptor

const file_wessley_ml_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x18wessley/ml/v1/chat.proto\x12\rwessley.ml.v1\"\xbd\x01\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\acontext\x18\x02 \x03(\tR\acontext\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x06 \x01(\x05R\tmaxTokens\"[\n" +
	"\fChatResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12\x1f\n" +
	"\vtokens_used\x18\x02 \x01(\x05R\n" +
	"tokensUsed\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"3\n" +
	"\tChatChunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done2\x94\x01\n" +
	"\vChatService\x12?\n" +
	"\x04Chat\x12\x1a.wessley.ml.v1.ChatRequest\x1a\x1b.wessley.ml.v1.ChatResponse\x12D\n" +
	"\n" +
	"ChatStream\x12\x1a.wessley.ml.v1.ChatRequest\x1a\x18.wessley.ml.v1.ChatChunk0\x01B\x1bZ\x19wessley-mvp/ml/proto;mlpbb\x06proto3"

var (
	file_wessley_ml_v1_chat_proto_rawDescOnce sync.Once
	file_wessley_ml_v1_chat_proto_rawDescData []byte
)

func file_wessley_ml_v1_chat_proto_rawDescGZIP() []byte {
	file_wessley_ml_v1_chat_proto_rawDescOnce.Do(func() {
		file_wessley_ml_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wessley_ml_v1_chat_proto_rawDesc), len(file_wessley_ml_v1_chat_proto_rawDesc)))
	})
	return file_wessley_ml_v1_chat_proto_rawDescData
}

var file_wessley_ml_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wessley_ml_v1_chat_proto_goTypes = []any{
	(*ChatRequest)(nil),  // 0: wessley.ml.v1.ChatRequest
	(*ChatResponse)(nil), // 1: wessley.ml.v1.ChatResponse
	(*ChatChunk)(nil),    // 2: wessley.ml.v1.ChatChunk
}
var file_wessley_ml_v1_chat_proto_depIdxs = []int32{
	0, // 0: wessley.ml.v1.ChatService.Chat:input_type -> wessley.ml.v1.ChatRequest
	0, // 1: wessley.ml.v1.ChatService.ChatStream:input_type -> wessley.ml.v1.ChatRequest
	1, // 2: wessley.ml.v1.ChatService.Chat:output_type -> wessley.ml.v1.ChatResponse
	2, // 3: wessley.ml.v1.ChatService.ChatStream:output_type -> wessley.ml.v1.ChatChunk
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wessley_ml_v1_chat_proto_init() }
func file_wessley_ml_v1_chat_proto_init() {
	if File_wessley_ml_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wessley_ml_v1_chat_proto_rawDesc), len(file_wessley_ml_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wessley_ml_v1_chat_proto_goTypes,
		DependencyIndexes: file_wessley_ml_v1_chat_proto_depIdxs,
		MessageInfos:      file_wessley_ml_v1_chat_proto_msgTypes,
	}.Build()
	File_wessley_ml_v1_chat_proto = out.File
	file_wessley_ml_v1_chat_proto_goTypes = nil
	file_wessley_ml_v1_chat_proto_depIdxs = nil
}
