// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wessley/ml/v1/embed.proto

package mlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_wessley_ml_v1_embed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wessley_ml_v1_embed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_wessley_ml_v1_embed_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	Dimensions    int32                  `protobuf:"varint,2,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_wessley_ml_v1_embed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wessley_ml_v1_embed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_wessley_ml_v1_embed_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedResponse) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *EmbedResponse) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

type EmbedBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedBatchRequest) Reset() {
	*x = EmbedBatchRequest{}
	mi := &file_wessley_ml_v1_embed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedBatchRequest) ProtoMessage() {}

func (x *EmbedBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wessley_ml_v1_embed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedBatchRequest.ProtoReflect.Descriptor instead.
func (*EmbedBatchRequest) Descriptor() ([]byte, []int) {
	return file_wessley_ml_v1_embed_proto_rawDescGZIP(), []int{2}
}

func (x *EmbedBatchRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

type EmbedBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*EmbedResponse       `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedBatchResponse) Reset() {
	*x = EmbedBatchResponse{}
	mi := &file_wessley_ml_v1_embed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedBatchResponse) ProtoMessage() {}

func (x *EmbedBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wessley_ml_v1_embed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedBatchResponse.ProtoReflect.Descriptor instead.
func (*EmbedBatchResponse) Descriptor() ([]byte, []int) {
	return file_wessley_ml_v1_embed_proto_rawDescGZIP(), []int{3}
}

func (x *EmbedBatchResponse) GetEmbeddings() []*EmbedResponse {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

var File_wessley_ml_v1_embed_proto protoreflect.FileDescriptor

const file_wessley_ml_v1_embed_proto_rawDesc = "" +
	"\n" +
	"\x19wessley/ml/v1/embed.proto\x12\rwessley.ml.v1\"\"\n" +
	"\fEmbedRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"G\n" +
	"\rEmbedResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x02 \x01(\x05R\n" +
	"dimensions\")\n" +
	"\x11EmbedBatchRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\"R\n" +
	"\x12EmbedBatchResponse\x12<\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x1c.wessley.ml.v1.EmbedResponseR\n" +
	"embeddings2\xa5\x01\n" +
	"\fEmbedService\x12B\n" +
	"\x05Embed\x12\x1b.wessley.ml.v1.EmbedRequest\x1a\x1c.wessley.ml.v1.EmbedResponse\x12Q\n" +
	"\n" +
	"EmbedBatch\x12 .wessley.ml.v1.EmbedBatchRequest\x1a!.wessley.ml.v1.EmbedBatchResponseB\x1bZ\x19wessley-mvp/ml/proto;mlpbb\x06proto3"

var (
	file_wessley_ml_v1_embed_proto_rawDescOnce sync.Once
	file_wessley_ml_v1_embed_proto_rawDescData []byte
)

func file_wessley_ml_v1_embed_proto_rawDescGZIP() []byte {
	file_wessley_ml_v1_embed_proto_rawDescOnce.Do(func() {
		file_wessley_ml_v1_embed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wessley_ml_v1_embed_proto_rawDesc), len(file_wessley_ml_v1_embed_proto_rawDesc)))
	})
	return file_wessley_ml_v1_embed_proto_rawDescData
}

var file_wessley_ml_v1_embed_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wessley_ml_v1_embed_proto_goTypes = []any{
	(*EmbedRequest)(nil),       // 0: wessley.ml.v1.EmbedRequest
	(*EmbedResponse)(nil),      // 1: wessley.ml.v1.EmbedResponse
	(*EmbedBatchRequest)(nil),  // 2: wessley.ml.v1.EmbedBatchRequest
	(*EmbedBatchResponse)(nil), // 3: wessley.ml.v1.EmbedBatchResponse
}
var file_wessley_ml_v1_embed_proto_depIdxs = []int32{
	1, // 0: wessley.ml.v1.EmbedBatchResponse.embeddings:type_name -> wessley.ml.v1.EmbedResponse
	0, // 1: wessley.ml.v1.EmbedService.Embed:input_type -> wessley.ml.v1.EmbedRequest
	2, // 2: wessley.ml.v1.EmbedService.EmbedBatch:input_type -> wessley.ml.v1.EmbedBatchRequest
	1, // 3: wessley.ml.v1.EmbedService.Embed:output_type -> wessley.ml.v1.EmbedResponse
	3, // 4: wessley.ml.v1.EmbedService.EmbedBatch:output_type -> wessley.ml.v1.EmbedBatchResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wessley_ml_v1_embed_proto_init() }
func file_wessley_ml_v1_embed_proto_init() {
	if File_wessley_ml_v1_embed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wessley_ml_v1_embed_proto_rawDesc), len(file_wessley_ml_v1_embed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wessley_ml_v1_embed_proto_goTypes,
		DependencyIndexes: file_wessley_ml_v1_embed_proto_depIdxs,
		MessageInfos:      file_wessley_ml_v1_embed_proto_msgTypes,
	}.Build()
	File_wessley_ml_v1_embed_proto = out.File
	file_wessley_ml_v1_embed_proto_goTypes = nil
	file_wessley_ml_v1_embed_proto_depIdxs = nil
}
